<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Checks whether the Vite dev server is currently running.
 *
 * Looks for the `hot` file written to the theme root on dev server
 * startup and removed on shutdown (see vite.config.js).
 *
 * @return bool True if the dev server is running, false otherwise.
 */
function pbtv_vite_is_dev_server_running(): bool {
	return file_exists( get_theme_file_path( 'hot' ) );
}

/**
 * Gets the Vite dev server base URL.
 *
 * Reads the contents of the `hot` file, which stores the URL the Vite
 * dev server is listening on (e.g. http://localhost:5173).
 *
 * @return string The dev server URL, or an empty string if unavailable.
 */
function pbtv_vite_dev_server_url(): string {
	return trim( (string) file_get_contents( get_theme_file_path( 'hot' ) ) );
}

/**
 * Retrieves the Vite production build manifest.
 *
 * Reads `assets/dist/.vite/manifest.json`, generated by Vite on build,
 * which maps source entry paths (e.g. `src/css/main.css`) to their
 * hashed output file paths for cache busting. The parsed result is
 * cached in a static variable for the duration of the request.
 *
 * @return array<string, array<string, mixed>> The decoded manifest, or an
 *                                              empty array if the manifest
 *                                              file does not exist.
 */
function pbtv_vite_manifest(): array {
	static $manifest = null;

	if ( null !== $manifest ) {
		return $manifest;
	}

	$manifest_path = get_theme_file_path( 'assets/dist/.vite/manifest.json' );

	if ( ! file_exists( $manifest_path ) ) {
		$manifest = array();

		return $manifest;
	}

	$contents = file_get_contents( $manifest_path );
	$manifest = $contents ? (array) json_decode( $contents, true ) : array();

	return $manifest;
}

/**
 * Enqueues the theme's front-end styles and scripts.
 *
 * In development, assets are served directly from the running Vite dev
 * server (with the Vite client script module for HMR). In production,
 * the built and hashed asset file is resolved from the Vite manifest and
 * enqueued as a regular stylesheet.
 *
 * @return void
 */
function pbtv_theme_enqueue_assets(): void {
	if ( pbtv_vite_is_dev_server_running() ) {
		$dev_server = pbtv_vite_dev_server_url();

		wp_enqueue_script_module( 'pbtv-vite-client', $dev_server . '/@vite/client' );
		wp_enqueue_script_module( 'pbtv-main', $dev_server . '/src/css/main.css' );

		return;
	}

	$manifest = pbtv_vite_manifest();
	$entry    = $manifest['src/css/main.css']['file'] ?? null;

	if ( ! $entry ) {
		return;
	}

	$theme = wp_get_theme();

	wp_enqueue_style(
		'pbtv-main',
		get_theme_file_uri( 'assets/dist/' . $entry ),
		array(),
		$theme->get( 'Version' )
	);
}

add_action( 'wp_enqueue_scripts', 'pbtv_theme_enqueue_assets' );
