<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Checks whether the Vite dev server is currently running.
 *
 * Looks for the `hot` file written to the theme root on dev server
 * startup and removed on shutdown (see vite.config.js).
 *
 * @return bool True if the dev server is running, false otherwise.
 */
function pbtv_vite_is_dev_server_running(): bool {
	return file_exists( get_theme_file_path( 'hot' ) );
}

/**
 * Gets the Vite dev server base URL.
 *
 * Reads the contents of the `hot` file, which stores the URL the Vite
 * dev server is listening on (e.g. http://localhost:5173).
 *
 * @return string The dev server URL, or an empty string if unavailable.
 */
function pbtv_vite_dev_server_url(): string {
	return trim( (string) file_get_contents( get_theme_file_path( 'hot' ) ) );
}

/**
 * Retrieves the Vite production build manifest.
 *
 * Reads `assets/dist/.vite/manifest.json`, generated by Vite on build,
 * which maps source entry paths (e.g. `src/css/main.css`) to their
 * hashed output file paths for cache busting. The parsed result is
 * cached in a static variable for the duration of the request.
 *
 * @return array<string, array<string, mixed>> The decoded manifest, or an
 *                                              empty array if the manifest
 *                                              file does not exist.
 */
function pbtv_vite_manifest(): array {
	static $manifest = null;

	if ( null !== $manifest ) {
		return $manifest;
	}

	$manifest_path = get_theme_file_path( 'assets/dist/.vite/manifest.json' );

	if ( ! file_exists( $manifest_path ) ) {
		$manifest = array();

		return $manifest;
	}

	$contents = file_get_contents( $manifest_path );
	$manifest = $contents ? (array) json_decode( $contents, true ) : array();

	return $manifest;
}

/**
 * Forces the Vite dev entries to be printed as `type="module"` script tags.
 *
 * `wp_enqueue_script_module()` is not an option here because its output is
 * not collected by `_wp_get_iframed_editor_assets()`, so it would never
 * reach the Post/Site Editor iframe. Registering these as regular scripts
 * (via `wp_enqueue_script()`) keeps them in `$wp_scripts`, which the iframe
 * asset collector does capture, while this filter restores the `module`
 * type the browser needs to actually run them.
 *
 * @param string $tag    The `<script>` tag markup.
 * @param string $handle The script's registered handle.
 * @return string The filtered script tag markup.
 */
function pbtv_vite_dev_script_module_tag( string $tag, string $handle ): string {
	if ( ! in_array( $handle, array( 'pbtv-vite-client', 'pbtv-main' ), true ) ) {
		return $tag;
	}

	return str_replace( ' src=', ' type="module" src=', $tag );
}

add_filter( 'script_loader_tag', 'pbtv_vite_dev_script_module_tag', 10, 2 );

/**
 * Enqueues the theme's styles and scripts for the front-end and the editor.
 *
 * Hooked on `enqueue_block_assets` so the same assets are also pulled into
 * the Post/Site Editor iframe, which is why Tailwind rules were missing
 * there when this only ran on `wp_enqueue_scripts` (a front-end-only hook).
 *
 * In development, assets are served directly from the running Vite dev
 * server (with the Vite client script for HMR). In production, the built
 * and hashed asset file is resolved from the Vite manifest and enqueued as
 * a regular stylesheet.
 *
 * @return void
 */
function pbtv_theme_enqueue_assets(): void {
	if ( pbtv_vite_is_dev_server_running() ) {
		$dev_server = pbtv_vite_dev_server_url();

		wp_enqueue_script( 'pbtv-vite-client', $dev_server . '/@vite/client', array(), null );
		wp_enqueue_script( 'pbtv-main', $dev_server . '/src/css/main.css', array( 'pbtv-vite-client' ), null );

		return;
	}

	$manifest = pbtv_vite_manifest();
	$entry    = $manifest['src/css/main.css']['file'] ?? null;

	if ( ! $entry ) {
		return;
	}

	$theme = wp_get_theme();

	wp_enqueue_style(
		'pbtv-main',
		get_theme_file_uri( 'assets/dist/' . $entry ),
		array(),
		$theme->get( 'Version' )
	);
}

add_action( 'enqueue_block_assets', 'pbtv_theme_enqueue_assets' );
